# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1024"]
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        entry: task ruff-lint
        language: system
        pass_filenames: false
        types:
          - python
      - id: ruff-format
        name: ruff-format
        entry: task ruff-format
        language: system
        pass_filenames: false
        types:
          - python
      - id: mypy
        name: mypy
        entry: task mypy
        language: system
        pass_filenames: false
        types:
          - python
      - id: deptry
        name: deptry
        entry: task deptry
        language: system
        pass_filenames: false
        types:
          - python
